update connect sensui wallet preset
suiet/wallet-kit pull request #124
Opened 2023-03-17 04:48 UTC by loclanhlung

update connect sensui wallet preset

2023-03-29 18:12 UTC, bruceeewong requested changes
Please reduce the base64 img size for further merging. Thanks

2023-04-03 02:04 UTC, djleo95 commented
@bruceeewong Thanks for responding. We'll handle it.

2023-04-03 02:20 UTC, djleo95 commented
@bruceeewong We reduced the size, please check again. Thanks.

2023-07-23 01:56 UTC, bruceeewong approved these changes

2023-07-23 01:57 UTC, merged